# Generated by Django 3.0 on 2019-12-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=200)),
                ('assunto', models.CharField(max_length=100)),
                ('editora', models.CharField(max_length=20)),
                ('isbn', models.CharField(max_length=20)),
                ('ano', models.DateField()),
            ],
        ),
    ]
